### ISSUE TITLE
Error when using . shortcut for current directory

### ISSUE THREAD

**Issue by username227** [OPSnet/audioinfo#1]
Hi,
I'm using Arch with the amd64 file. The script works just fine to generate the file when the full directory path. However, it does not seem to work at all when I use the . to indicate the current directory. It also seems not to recognize the ~ symbol to indicate the Home/_user_ directory.

**Comment by spider-ops** [comment]
Please try the latest v0.0.2 version. From my testing it unwraps path correctly

**Comment by username227** [comment]
Yes, that's better. The simple command `audioinfo --input . ./audioinfo.txt` now works as expected.
